AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  arcus-read-only

  Proxy for arcus-python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: arcus_read_only/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          ARCUS_API_KEY: !Ref ARCUS_API_KEY
          ARCUS_SECRET_KEY: !Ref ARCUS_SECRET_KEY
          SENTRY_DSN: !Ref SENTRY_DSN
      Events:
        Proxy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{ruta_arcus}
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ProxyFunction:
    Description: "Proxy Lambda Function ARN"
    Value: !GetAtt ProxyFunction.Arn
  ProxyFunctionIamRole:
    Description: "Implicit IAM Role created for Proxy function"
    Value: !GetAtt ProxyFunctionRole.Arn
